export interface Ubicacion {
    $key: string,
    date: string,
    latitud: number,
    longitud: number,
    altura: number,
    velocidad: number,
    actividad: string,
    confianza: string,
    azimuth: number,
    X:number,
    Y:number,
    Z:number,
    CantSat:number,
    postionDop:string,
    horizontalDop:string,
    verticalDop:string,
    geoidHeight:string,
    ageOfGpsData:string,
    antennaAltitud:string,
    listaSatelite:Array<satellite>,
    temperatura:string,
    uid: string,   
}

interface satellite{ 
    azimuth: number,
    elevation:number,
    prn:number,
    signalStrength:number,
    snr:number,
    type:string,
    used:boolean,
    validSatellite:boolean,
    x:number,
    y:number,
    z:number,
}